apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# base_volume_localpath もしくは、 base_volume_nfs から派生する

# 親ファイル
bases:
- ../base_common
# Volume - NFS の場合
- ../base_volume_nfs
# Volume - LocalPath の場合
# - ../base_volume_localpath

# パッチファイル
patches:
- workspace.yaml
- deployment.yaml
# Volume - NFS の場合
- volume-nfs.yaml
# Volume - LocalPath の場合
# - volume-localpath.yaml

# ConfigMap 自動マージ
configMapGenerator:
- name: common-env
  behavior: merge
  env: common.env
