apiVersion: v1
kind: Pod
metadata:
  name: workspace
  labels:
    app: k8s-workspace
spec:
  containers:
  - name: workspace
    volumeMounts:
      - name: volume-data
        mountPath: /usr/src/app
  volumes:
    - name: volume-data
      persistentVolumeClaim:
        claimName: local-volume-claim
