apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: k8s-workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-workspace
  template:
    metadata:
      labels:
        app: k8s-workspace
    spec:
      containers:
      - name: deployment
        image: node:lts-stretch
        command:
          - /bin/bash
          - -c
          - while true; do
              sleep 1;
            done
        resources:
          requests:
            cpu: 1000m
            memory: 1000Mi
        envFrom:
        - configMapRef:
            name: common-env
        volumeMounts:
          - name: volume-data
            mountPath: /usr/src/app
      volumes:
        - name: volume-data
          persistentVolumeClaim:
            claimName: local-volume-claim
